-- Adds a dedicated meal_guidelines column, generated by its own AI step
-- (Breakfast/Lunch/Dinner, functional-nutrition framing) instead of being
-- repurposed from the "Diet protocol" clinical-notes section — that section
-- stays general-purpose dietary intervention text, still used as-is for
-- recipe-bank keyword matching (see lib/pdf/matchRecipes.ts) and the
-- Biomarkers/Supplements/Red-flags pages, so it was not safe to overload
-- with meal-timing content.
--
-- Additive and nullable, same pattern as v35/v36: existing rows are left
-- alone, and buildGuideData() falls back to the old diet-protocol-derived
-- default when this is null (older roadmaps, or before this migration runs).
alter table public.roadmaps
  add column if not exists meal_guidelines text;

alter table public.roadmap_versions
  add column if not exists meal_guidelines text;
